apiVersion: apps/v1
kind: Deployment
metadata:
  name: pusher-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pusher
  template:
    metadata:
      labels:
        app: pusher
    spec:
      containers:
        - name: pusher
          image: saumilbisht/buptime-pusher:6e9fe32d04432b8d39a454180e38cdb89ae8a822
          envFrom:
            - secretRef:
                name: uptime-secrets