apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: saumilbisht/buptime-worker:latest
          env:
            - name: REGION_ID
              valueFrom:
                configMapKeyRef:
                  name: region-config
                  key: region_id
            - name: WORKER_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          envFrom:
            - secretRef:
                name: uptime-secrets